Changing timestamps in vehicle controller and pose messages to micros…
PlanetaryRobotics/moonranger-rover-messages pull request #10
Opened 2021-11-02 15:37 UTC by bkolligs

Changing timestamps in some messages from nano to micro seconds to better use the CFE conversion time functions. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have read and followed the `CONTRIBUTING.md` file
- [ ] I have applied the .clang-format file to my changes
- [ ] I have commented my code using Doxygen style comments (see Contributing MD for examples), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the design documentation 
- [ ] I have updated any relevant parameters in the internal ICD
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this is a bug-fix, I have added tests that can catch similar bugs in the future
- [ ] New and existing unit tests pass locally with my changes
- [ ] For cfe apps I have reserved an empty address for my msgs_ids and perf_ids from the [tracking list](https://docs.google.com/spreadsheets/d/1yRUhNTRBOiGLswlsWftNaYlwGKDeNQ_fCnDYFrc_7fU/edit#gid=772812381) and checked that it does not clash with other apps

2021-11-02 17:07 UTC, kangkelvin requested changes

2021-11-02 17:07 UTC, kangkelvin commented on fsw/public_inc/body_velocity_msg.h
> +  uint64 timeStamp;   // microseconds
if you want to use cFE time, then your timestamp should be of struct `CFE_TIME_SysTime_t` defined at `cfe_time.h`
```
CFE_TIME_SysTime_t timeStamp;
```
And when you assign timestamps you use:
```
bodyVelocity.timeStamp = CFE_TIME_GetTime();
```

2021-11-02 17:12 UTC, bkolligs commented on fsw/public_inc/body_velocity_msg.h
> +  uint64 timeStamp;   // microseconds
Can I use the conversion function CFE_TIME_Sub2Micro?

2021-11-03 20:09 UTC, bdcmu commented on fsw/public_inc/body_velocity_msg.h
> +  uint64 timeStamp;   // microseconds
I think this is fully resolved based on the last commit switching to CFE_TIME_SysTime_t

BTW don't ever pass more than 999999 (1 second worth of microsecods)  to CFE_TIME_Sub2Micro or it will return MAX UINT

2021-11-05 22:05 UTC, kangkelvin approved these changes
LGTM

2021-11-10 20:30 UTC, merged