Implement Planner Messages
PlanetaryRobotics/moonranger-rover-messages pull request #105
Opened 2022-04-02 21:06 UTC by epicstar

## Description

From PlanetaryRobotics/moonranger-ground-backend#205, send and receive Planner app messages.

## How has this been tested?

TODO

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have read and followed the `CONTRIBUTING.md` file
- [ ] I have applied the .clang-format file to my changes
- [ ] I have commented my code using Doxygen style comments (see Contributing MD for examples), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the design documentation 
- [ ] I have updated any relevant parameters in the internal ICD
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this is a bug-fix, I have added tests that can catch similar bugs in the future
- [ ] New and existing unit tests pass locally with my changes
- [ ] For cfe apps I have reserved an empty address for my msgs_ids and perf_ids from the [tracking list](https://docs.google.com/spreadsheets/d/1yRUhNTRBOiGLswlsWftNaYlwGKDeNQ_fCnDYFrc_7fU/edit#gid=772812381) and checked that it does not clash with other apps
- [ ] For new added message types, there is a timestamp included via either an explicit timestamp variable in the struct or buried in the a tlmHeader.

2022-04-06 03:01 UTC, tenzincrouch commented
the prior PR has been merged, if that was what was holding this back you can update it now.

2022-04-07 00:53 UTC, epicstar commented
@zhaowenzi and @tenzincrouch. There is a merge conflict here. It would be nice if I could get assistance to fix the merge conflicts. I don't have any idea which branch @zhaowenzi 's commits are coming from.

2022-04-11 11:07 UTC, ashwin21rao requested changes

2022-04-11 11:07 UTC, ashwin21rao commented on message-utilities/include/message_builder.h
> +    PLANNER_HkTlm_t PlannerHk_Tlm;
Please move line 66 to the section above (for telemetry messages).
Other than this, LGTM.

2022-04-11 13:40 UTC, epicstar commented
@ashwin21rao thank you for the review. Please check again (I resolved the convo.

2022-04-12 10:48 UTC, ashwin21rao approved these changes
LGTM

2022-04-12 10:50 UTC, merged