Add Field for iOBC Reboot Reason
PlanetaryRobotics/moonranger-rover-messages pull request #161
Opened 2023-02-01 04:35 UTC by mlang25

Adds a field in the OBC health payload that will indicate why the iOBC was reset. The source of this field will contain the contents of the AT91SAM9G20 RSTC_SR register.

## Description

## 

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have read and followed the `CONTRIBUTING.md` file
- [ ] I have applied the .clang-format file to my changes
- [ ] I have commented my code using Doxygen style comments (see Contributing MD for examples), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the design documentation 
- [ ] I have updated any relevant parameters in the internal ICD
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this is a bug-fix, I have added tests that can catch similar bugs in the future
- [ ] New and existing unit tests pass locally with my changes
- [ ] For cfe apps I have reserved an empty address for my msgs_ids and perf_ids from the [tracking list](https://docs.google.com/spreadsheets/d/1yRUhNTRBOiGLswlsWftNaYlwGKDeNQ_fCnDYFrc_7fU/edit#gid=772812381) and checked that it does not clash with other apps
- If any message is changed, removed, or added:
  - [ ] Please contact `#software` on Slack about the change(s)
  - [ ] **ONLY IF TELEMETRY MESSAGE** (for now): `./message-utilities/src/utilities.c` is updated with the correct field(s) properly marshalled to JSON **(IMPORTANT)**
  - If a new struct/message is added:
    - [ ] There is a timestamp included via either an explicit timestamp variable in the struct or buried in the a tlmHeader
  - If any of the existing struct's properties change in any way (property name change, property moves around in the struct, property removed):
    - [ ] **Breaking change** is checkmarked above as any change will affect every software downstream

2023-02-09 21:28 UTC, epicstar requested changes
Please add these properties to the OBC Health Payload to json `utilities.c` logic. Please follow the pattern in the code added in #162 inside utilities.c: https://github.com/PlanetaryRobotics/moonranger-rover-messages/pull/162/files#diff-c33a01146184104e5aa68d3d161d5f2bd0fc91005cdbb5b81d16778193cece64

2023-02-10 19:31 UTC, epicstar submitted a review, later dismissed
I'm preapproving. The one change in parseTelemetryOBC() (line 365) is good. The others I've commented on as being handled in #164. If not reverted, we will have merge conflicts, but that is not a hard problem to fix anyway.

Thank you @mlang25!!

2023-02-10 19:31 UTC, epicstar commented on message-utilities/src/utilities.c
> +    //cJSON_AddNumberToObject(p, "CommandErrorCounter", data.CommandErrorCounter);
This can be reverted. This is handled in #164. NBD if this stays however, but we just may end up with a merge conflict that should be a trivial fix.

2023-02-10 19:31 UTC, epicstar commented on message-utilities/src/utilities.c
> +    //cJSON_AddNumberToObject(p, "GoalCounter", data.GoalCounter);
This can be reverted. This is handled in #164. NBD if this stays however, but we just may end up with a merge conflict that should be a trivial fix.

2023-02-10 19:31 UTC, epicstar commented on message-utilities/src/utilities.c
> +    //cJSON_AddNumberToObject(p, "CommandErrorCounter", data.CommandErrorCounter);
This can be reverted. This is handled in #164. NBD if this stays however, but we just may end up with a merge conflict that should be a trivial fix.

2023-02-12 05:25 UTC, mlang25 commented
@epicstar Do you mind re-approving the PR? I think the update requires a new approval

2023-02-12 06:22 UTC, epicstar approved these changes
We're getting really close!! Please see comments. Once done, I'll approve and we can merge. Thank you!!

2023-02-12 06:22 UTC, epicstar commented on message-utilities/src/utilities.c
> +    cJSON_AddNumberToObject(p, "CommandErrorCounter", data.CommandErrorCounter);
```suggestion
```

Please remove these lines. These no longer exist in `POSE_HkTlm_t`: https://github.com/PlanetaryRobotics/moonranger-rover-messages/blob/scratch/iobc_reboot_reason/fsw/public_inc/pose_estimator_msgs.h#L57

2023-02-12 06:22 UTC, epicstar commented on message-utilities/src/utilities.c
> +    cJSON_AddNumberToObject(p, "GoalCounter", data.GoalCounter);
```suggestion
```

Please remove these lines. These lines no longer are in the `MAPPER_HkTlm_t` struct. https://github.com/PlanetaryRobotics/moonranger-rover-messages/blob/f7178a96f7f1721013aa4c9bd55bb8ae3caabdc9/fsw/public_inc/mapper_msgs.h#L73

2023-02-12 06:23 UTC, epicstar requested changes
See comments above. We're getting close. Thank you!!

2023-02-27 23:56 UTC, epicstar approved these changes
@mlang25 this is good thank you!!

2023-03-01 00:24 UTC, merged