Updated pointcloud message struct
PlanetaryRobotics/moonranger-rover-messages pull request #23
Opened 2021-11-25 22:16 UTC by ankurbodhe

## Description

This PR updates the PointCloud message structure. THis is done in accordance with the design documentation and discussion with the perception team. 
## 

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] I have read and followed the `CONTRIBUTING.md` file
- [ ] I have applied the .clang-format file to my changes
- [ ] I have commented my code using Doxygen style comments (see Contributing MD for examples), particularly in hard-to-understand areas
- [X] I have made corresponding changes to the design documentation 
- [ ] I have updated any relevant parameters in the internal ICD
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] If this is a bug-fix, I have added tests that can catch similar bugs in the future
- [ ] New and existing unit tests pass locally with my changes
- [ ] For cfe apps I have reserved an empty address for my msgs_ids and perf_ids from the [tracking list](https://docs.google.com/spreadsheets/d/1yRUhNTRBOiGLswlsWftNaYlwGKDeNQ_fCnDYFrc_7fU/edit#gid=772812381) and checked that it does not clash with other apps
- [ ] For new added message types, there is a timestamp included via either an explicit timestamp variable in the struct or buried in the a tlmHeader.

2021-11-26 04:13 UTC, margareh requested changes
Please discuss the point cloud data structure with the perception team. I'm not sure we need this extra file given that they already have the point cloud type defined elsewhere. However, we should also confirm that that type def is fine where it is (in `sb_transport_lib.h` [here](https://github.com/PlanetaryRobotics/moonranger-rover-flight/blob/main/central/apps/sb_transport_lib/fsw/public_inc/sb_transport_lib.h)) instead of in the common messages library.

2021-11-26 04:13 UTC, margareh commented on fsw/public_inc/point_cloud_msg.h
> +}MOONRANGER_Pcl_t;
This type is already defined in sb_transport_lib.h ([here](https://github.com/PlanetaryRobotics/moonranger-rover-flight/blob/main/central/apps/sb_transport_lib/fsw/public_inc/sb_transport_lib.h)). We shouldn't have competing type defs. I think we should rely on the one in the SB transport library since that is what perception appears to be using but move that definition here. @kangkelvin @tenzincrouch what do you think? Is there a reason the point cloud type def should stay in sb_transport_lib instead of being in the common messages library?

2021-11-26 04:13 UTC, margareh commented on fsw/public_inc/point_cloud_msg.h
> +} OS_PACK MOONRANGER_Pcl_Tlm_t;
If point clouds aren't being sent via the software bus, do we need a telemetry header/packet? We should think about this more/talk to the perception people who have been working on the point cloud data structure/transport.

2021-11-26 04:13 UTC, margareh commented on fsw/public_inc/point_cloud_msg.h
> +#define MOONRANGER_POSE_LNGTH sizeof(MOONRANGER_Pcl_t)
This variable and the one below it are named incorrectly (should be something like `MOONRANGER_PCL_LNGTH` and `MOONRANGER_PCL_TLM_LNGTH` or something similar since it's a point cloud and not a pose message).

2021-11-29 20:25 UTC, tenzincrouch commented on fsw/public_inc/point_cloud_msg.h
> +}MOONRANGER_Pcl_t;
I had originally planned to have each individual message have its own .h file so it didnt need to be included everywhere. But for the case of th SB transport lib with all of the large messages this approach should be fine.

2021-12-03 20:35 UTC, margareh commented
@ankurbodhe @tenzincrouch I think we can delete this PR as we don't want the point cloud defined here/have it defined elsewhere. Correct?

2021-12-04 03:01 UTC, closed without merging